# Generated by Django 4.1.5 on 2023-02-12 15:12

from django.db import migrations

def create_data(apps, schema_editor):
  Student = apps.get_model('students', 'Student')
  Student(name="Marianne Salomao", email="marianne@email.com", document="123456789", phone="1234567").save()

class Migration(migrations.Migration):

  dependencies = [
    ("students", "0001_initial"),
  ]

  operations = [
    migrations.RunPython(create_data)
  ]
